apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: elasticsearch-discovery
  labels:
    app: elasticsearch
    role: master
spec:
  selector:
    app: elasticsearch
    role: master
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: node-to-node
---
apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: elasticsearch-logging
  labels:
    app: elasticsearch
    role: data
spec:
  selector:
    app: elasticsearch
    role: data
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: node-to-node
