apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: storage
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: 30002
  selector:
    app: minio
